### PR TITLE
Added possibility to add multiple tags to image

### PR DESCRIPTION
**Pull request by argoyle**

### CODE REVIEW

**Comment by marcuslonnberg** [comment]
Great Jocke!

I think that we should support that the additional tags can have a completely different image name as well. Example:
```scala
imageName in docker := ImageName("abc/abc:v1")
additonalTags in docker := Seq(ImageName("abc/abc:latest"), ImageName("xyz/xyz:v1"))
```

And if we make that change then it would probably be clearer to use:
```scala
imageNames in docker := Seq(ImageName("abc/abc:v1"), ImageName("abc/abc:latest"), ImageName("xyz/xyz:v1"))
```
An empty sequence of images would be ok, it will then build the image without any name.

**Comment by argoyle** [comment]
Sounds like a good idea. Want me to do the change and create a new pull request?

**Comment by marcuslonnberg** [comment]
You can update this PR if you want.

**Comment by argoyle** [comment]
Ok. Changes pushed now.

**Comment by marcuslonnberg** [comment]
Sorry for the delay. The changes looks good!
Will merge them tomorrow, need to make sure we have backwards compatibility with `imageName`.

**Pull request merged**
