### PR TITLE
added docker image labels

### PR DESCRIPTION
**Pull request by matlockx**
* simple extension for labels (needs docker >= 1.6)

### CODE REVIEW

**Comment by matlockx** [comment]
hm, there is a strange server access error. cannot see how that could be related to my change....

**Comment by marcuslonnberg** [comment]
Looks nice!

I looked at the documentation for LABEL. We should support multiple key-value pairs in the same instruction and support whitespaces. I think it can be implemented in the same way Env is.

The build error seems to be unrelated. In the first run there where 2 successful builds.

**Comment by matlockx** [comment]
Ok, I go for it and update the pr

**Comment by matlockx** [comment]
almost the same as env now ;)

**Comment by marcuslonnberg** [comment]
The Label class looks good now. But in `DockerfileCommands` there should be `label(labels: Map[String, String])`, `label(labels: (String, String)*)` and `labelRaw(labels: String)` methods to match `env`.

If you can please add some test in `InstructionsSpec` for Label to check that escaping of whitespaces and such works properly.

What changes have been done to the README? Looks like there is a lot of changes to the line breaks.
I see that you added label in one example for a Dockerfile. I rather see that you add that to `DockerfileExamples.scala` and/or the other examples in order to keep the README as simple as possible.

**Comment by matlockx** [comment]
- [x] DockerfileCommands
- [x] Tests in InstructionsSpec
- [x] Reformatted README again ;)
- [x] added dedicated label test in sbt-test

**Comment by marcuslonnberg** [comment]
It looks very good now! Thanks!
Will release a new version this week.

**Comment by matlockx** [comment]
welcome. thanks for your great plugin though :)

**Pull request merged**
